#!/bin/bash

for arg in $@; do # make folders or file paths absolute before cd'ing 
    [ -d "$arg" ] || [ -f "$arg" ] && arg=$(readlink -f "$arg")
    arg_new="$arg_new $arg"
done
cd $( dirname $( readlink -f $0 ))
[ ! -d "node_modules" ] && npm install
echo "-- checking for forever"
[ -z "$( command -v forever )" ] && {
    sudo -H npm install -g forever
}
forever \
--minUptime 1000 \
--spinSleepTime 1000 \
--watch \
--watchIgnore '*.log' \
d3-wb-server.js $arg_new
