#!/bin/bash

for arg in $@; do # make folders or file paths absolute before cd'ing 
    [ -d "$arg" ] || [ -f "$arg" ] && arg=$(readlink -f "$arg")
    arg_new="$arg_new $arg"
done
cd $( dirname $( readlink -f $0 ))
[ ! -d "node_modules" ] && npm install
node d3-wb-server.js $arg_new
