#!/bin/bash

cd $( dirname $( readlink -f $0 ))
[ ! -d "node_modules" ] && npm install
echo "-- checking for browser-sync"
[ -z "$( command -v browser-sync )" ] && {
    sudo -H npm install -g browser-sync
}
echo "-- searching for content folder"
content="default-content"
content_alt=$( echo $@ | tr " " "\n" | grep "\-i" -A1 | tail -n1 )
[ ! -z $content_alt ] && content=$content_alt
echo "-- content folder is: $content"
echo "-- starting server"
./start $@ &
browser-sync start --proxy "$( hostname ):50321" \
--files d3-wb-server.js d3-wb-server/* d3-wb/* ${content}/*
